Document: freshen
Title: Debian freshen Manual
Author: <insert document author here>
Abstract: This manual describes what freshen is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freshen/freshen.sgml.gz

Format: postscript
Files: /usr/share/doc/freshen/freshen.ps.gz

Format: text
Files: /usr/share/doc/freshen/freshen.text.gz

Format: HTML
Index: /usr/share/doc/freshen/html/index.html
Files: /usr/share/doc/freshen/html/*.html
